name: CI
on: 
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    runs-on: micro-ui-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

