name: Node.js CI
on:
  workflow_call:

jobs:
  Security_checke:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: trivy installing
      run: |
        iwr "https://github.com/aquasecurity/trivy/releases/download/v0.71.0/trivy_0.71.0_windows-64bit.zip" -OutFile "trivy.zip"
        Expand-Archive -Path "trivy.zip" -DestinationPath ".\trivy" -Force
        .\trivy\trivy.exe version
    - name: trivy_scanning
      run: .\trivy\trivy.exe fs --format table -o fs-report.json .

  Security_scanning:
    runs-on: self-hosted
    needs: Security_checke
    steps: 
    - uses: actions/checkout@v4
    - name: install Gitleaks
      run: |
        winget install -e --id Gitleaks.Gitleaks
        exit 0
    - name: Gitleaks checks
      run: | 
        .\gitleaks_8.18.0_windows_x64\gitleaks.exe
        .\gitleaks_8.18.0_windows_x64\gitleaks.exe detect --source . --report-format json --report-path gitleaks-report.json
        
